# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-25 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='article_up',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
