# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-26 02:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20190325_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_down',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_up',
        ),
    ]
