# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-26 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20190326_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_doen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='article_up',
            field=models.IntegerField(default=0),
        ),
    ]
